### ISSUE TITLE
Edge doesn't display dependency check results

### ISSUE THREAD

**Issue by maxbraun** [dependency-check/dependency-check-sonar-plugin#216] opened 2020-02-11 16:21 UTC
**Describe the bug**
Edge doesn't display dependency check results with warning SEC7131

**To Reproduce**
It would be helpful when you support us with [example](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/master/examples) projects.
1. Install '...'
2. Run '....'
3. Login to '....'

**Current behavior**
Edge doesn't show the dependency check result page. it stays empty. Egde seems to have problems with the IFrame Setup, complaining about issues in iframe sandbox. Chrome shows the page.

**Expected behavior**
Edge should show dependency check results

**Screenshots**
I just made a screenshot of a broken project, but other projects have the same issue.

![err2](https://user-images.githubusercontent.com/366573/74255284-ec174a00-4cf1-11ea-85ab-ed26c9099572.png)

![err1](https://user-images.githubusercontent.com/366573/74255279-eae61d00-4cf1-11ea-9af4-1a2dc6481891.png)

**Versions (please complete the following information):**
-   Edge 44.18362
-   dependency-check (org.owasp:dependency-check-maven:5.2.4)
-   sonarqube  7.9.1
-   dependency-check-sonar-plugin 2.0.2

**Additional context**
As far as I can see, other issues are related to missing html report generation, this seems more related to the handling of the HTML Report in the iFrame…  
Its not a vanila Edge. System is managed.

**Comment by Reamer** [comment] 2020-02-25 16:52
Hi @maxbraun,
can you check, if the [pre-release](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/tag/2.0.3-SNAPSHOT) solves your issue. This pre-release is based on [rewrite_javascript branch](https://github.com/dependency-check/dependency-check-sonar-plugin/tree/rewrite_javascript).

**Comment by Vampire** [comment] 2020-02-25 17:59
According to https://caniuse.com/#feat=iframe-srcdoc Edge 44 does not know the used `srcdoc` element, but Edge 79 does support it.
Additionally you might need to use `options.el.appendChild` instead of `options.el.append`.

Regarding the pre-release, same as in other comment, it is shown, but styling and scripts are broken.

**Comment by maxbraun** [comment] 2020-03-04 17:37
Hey Guys, 
sorry for late reply. I can confirm its working fine with the version from the rewrite branch.
Cheers, Max

**Comment by Reamer** [comment] 2020-03-17 15:22
Fixed by #221

**Comment by Vampire** [comment] 2020-03-24 17:06
Just tried the latest `master`, Edge 41.16299.1480.0 does not display the report.
I see in the network monitor that the JSON is downloaded, but it is not displayed.

**Comment by Reamer** [comment] 2020-03-24 17:57
I have no access to a windows 10 system. So I'm not able to reproduce this issue.

**Comment by Vampire** [comment] 2020-03-24 17:59
And I don't like Edge, I thought I just give it a try for you and see whether it works.
I'm sorry, but I don't care enough about Edge to have a look myself.

**Comment by alixwar** [comment] 2020-07-30 10:46
I'm able to see dependency check results using Edge.

My setup:
- Windows 10
- Edge version 84.0.522.48
- SonarQube 8.3.1 (Enterprise Edition)
- Dependency check plugin 2.0.5

![edge-works](https://user-images.githubusercontent.com/5415786/88914304-ba277f00-d262-11ea-9552-481efd10a17b.jpg)

**Comment by Reamer** [comment] 2020-07-30 11:24
Edge is now based on chromium. https://blogs.windows.com/windowsexperience/2018/12/06/microsoft-edge-making-the-web-better-through-more-open-source-collaboration/

**Closed by Reamer** 2020-07-30 11:24 UTC
Labels: bug
