### ISSUE TITLE
Is dependency-check-sonar-plugin compatible with Sonarqube EE 9.4?

### ISSUE THREAD

**Issue by shafemoh** [dependency-check/dependency-check-sonar-plugin#667] opened 2022-06-11 15:19 UTC
Hi team,
we are currently hosting Sonarqube EE 9.2.4 and we will be upgrading to Sonarqube 9.4.0. We are currently using [sonar-dependency-check-plugin-2.0.8.jar](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar).
Should we upgrade the Dependency check plugin to some higher version (if so, to which version ? )
OR Can we stay on [sonar-dependency-check-plugin-2.0.8.jar](https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.8/sonar-dependency-check-plugin-2.0.8.jar) ?

Also asked here: https://github.com/dependency-check/dependency-check-sonar-plugin/issues/666

Regards @shafemoh

**Comment by Reamer** [comment] 2022-06-12 11:56
Duplicate of #666

**Closed by Reamer** 2022-06-12 11:56 UTC
